/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmproject;

//import com.sun.glass.events.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Faraday
 */
public class WekaPinUI extends javax.swing.JFrame {

    String display = "";
//    Boolean okbtn = false;
    
    public WekaPinUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pinField = new javax.swing.JPasswordField();
        clearBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        endeleaBtn = new javax.swing.JButton();
        kutokaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setBackground(new java.awt.Color(204, 102, 0));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Weka nambari yako ya siri");

        pinField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pinField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinFieldActionPerformed(evt);
            }
        });
        pinField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinFieldKeyTyped(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 255, 255));
        clearBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        clearBtn.setText("Futa");
        clearBtn.setBorder(null);
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        nineBtn.setBackground(new java.awt.Color(255, 255, 255));
        nineBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmproject/t9.PNG"))); // NOI18N
        nineBtn.setBorder(null);
        nineBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });

        sevenBtn.setBackground(new java.awt.Color(255, 255, 255));
        sevenBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        sevenBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmproject/t7.PNG"))); // NOI18N
        sevenBtn.setBorder(null);
        sevenBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });

        eightBtn.setBackground(new java.awt.Color(255, 255, 255));
        eightBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eightBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmproject/t8.PNG"))); // NOI18N
        eightBtn.setBorder(null);
        eightBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });

        fourBtn.setBackground(new java.awt.Color(255, 255, 255));
        fourBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fourBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmproject/t4.PNG"))); // NOI18N
        fourBtn.setBorder(null);
        fourBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });

        fiveBtn.setBackground(new java.awt.Color(255, 255, 255));
        fiveBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fiveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmproject/t5.PNG"))); // NOI18N
        fiveBtn.setBorder(null);
        fiveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });

        oneBtn.setBackground(new java.awt.Color(255, 255, 255));
        oneBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        oneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmproject/t1.PNG"))); // NOI18N
        oneBtn.setBorder(null);
        oneBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });

        sixBtn.setBackground(new java.awt.Color(255, 255, 255));
        sixBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        sixBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmproject/t6.PNG"))); // NOI18N
        sixBtn.setBorder(null);
        sixBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });

        threeBtn.setBackground(new java.awt.Color(255, 255, 255));
        threeBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        threeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmproject/t3.PNG"))); // NOI18N
        threeBtn.setBorder(null);
        threeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });

        zeroBtn.setBackground(new java.awt.Color(255, 255, 255));
        zeroBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        zeroBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmproject/t0.PNG"))); // NOI18N
        zeroBtn.setBorder(null);
        zeroBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });

        twoBtn.setBackground(new java.awt.Color(255, 255, 255));
        twoBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        twoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmproject/t2.PNG"))); // NOI18N
        twoBtn.setBorder(null);
        twoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });

        endeleaBtn.setBackground(new java.awt.Color(255, 255, 255));
        endeleaBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        endeleaBtn.setText("Endelea");
        endeleaBtn.setBorder(null);
        endeleaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        endeleaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endeleaBtnActionPerformed(evt);
            }
        });

        kutokaBtn.setBackground(new java.awt.Color(255, 255, 255));
        kutokaBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        kutokaBtn.setText("Kutoka");
        kutokaBtn.setBorder(null);
        kutokaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kutokaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kutokaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(kutokaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pinField)
                            .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(zeroBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(twoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endeleaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endeleaBtn)
                    .addComponent(kutokaBtn))
                .addGap(18, 18, 18)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(528, 444));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinFieldActionPerformed

    private void endeleaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endeleaBtnActionPerformed
        DashboardKIS das = new DashboardKIS();
        int temp = Integer.parseInt(pinField.getText());
        try{
            String sql = "SELECT * FROM customer_id WHERE customeID = '"+Welcome.loginID+"'";
            Connection conn = ATMdb.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                int pin = Integer.parseInt(rs.getString("pin"));
                if(pin==temp){
                    JOptionPane.showMessageDialog(null, "Imekamilika kwa mafanikio!");
                    Welcome w = new Welcome();
                    
                    File f;
                    if(new File(Welcome.name+".txt").exists()){
                        
                    }else{
                        w.setFile(Welcome.name);
                    }
                    
                    dispose();
                    das.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Nambari ya siri si sahihi!Jaribu tena!");
                    pinField.setText("");
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_endeleaBtnActionPerformed

    private void kutokaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kutokaBtnActionPerformed
        dispose();
        Welcome ins = new Welcome();
        ins.setVisible(true);
    }//GEN-LAST:event_kutokaBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        // TODO add your handling code here:
        display = pinField.getText();
        pinField.setText(display + "0");
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        // TODO add your handling code here:
        display = pinField.getText();
        pinField.setText(display + "1");
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        // TODO add your handling code here:
        display = pinField.getText();
        pinField.setText(display + "2");
    }//GEN-LAST:event_twoBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        // TODO add your handling code here:
        display = pinField.getText();
        pinField.setText(display + "3");
    }//GEN-LAST:event_threeBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        // TODO add your handling code here:
        display = pinField.getText();
        pinField.setText(display + "4");
    }//GEN-LAST:event_fourBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        // TODO add your handling code here:
        display = pinField.getText();
        pinField.setText(display + "5");
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        // TODO add your handling code here:
        display = pinField.getText();
        pinField.setText(display + "6");
    }//GEN-LAST:event_sixBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        // TODO add your handling code here:
        display = pinField.getText();
        pinField.setText(display + "7");
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        // TODO add your handling code here:
        display = pinField.getText();
        pinField.setText(display + "8");
    }//GEN-LAST:event_eightBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        // TODO add your handling code here:
        display = pinField.getText();
        pinField.setText(display + "9");
    }//GEN-LAST:event_nineBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        pinField.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void pinFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinFieldKeyTyped
        // TODO add your handling code here:
     /*   char iNumber = evt.getKeyChar();
            if(!(Character.isDigit(iNumber))
                    || (iNumber == KeyEvent.VK_BACKSPACE)
                    || (iNumber == KeyEvent.VK_DELETE)){
                evt.consume();
            }    */
    }//GEN-LAST:event_pinFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WekaPinUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WekaPinUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WekaPinUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WekaPinUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WekaPinUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton endeleaBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kutokaBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JPasswordField pinField;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
